blank_issues_enabled: true
contact_links:
  - name: README / FAQ
    url: https://github.com/Floki89/FreshWin#faq
    about: Many questions are already answered here / Viele Fragen sind hier schon beantwortet
